-- Skema backend CekPinjol untuk Supabase PostgreSQL.
-- Tanggal dan JSON sengaja tetap TEXT, sedangkan flag tetap INTEGER, agar
-- perilaku API sama dengan penyimpanan SQLite yang sudah ada.

CREATE TABLE IF NOT EXISTS public.app_schema_migrations (
  filename TEXT PRIMARY KEY,
  checksum TEXT NOT NULL,
  applied_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  )
);

CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 2 AND 100),
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'blocked')),
  blocked_at TEXT,
  blocked_by TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  blocked_reason TEXT,
  force_password_change INTEGER NOT NULL DEFAULT 0 CHECK (force_password_change IN (0, 1)),
  last_login_at TEXT,
  created_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  updated_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  deleted_at TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_nocase_uq
ON public.users (lower(email));

CREATE TABLE IF NOT EXISTS public.sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  ip_address TEXT,
  user_agent TEXT,
  created_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  last_seen_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  expires_at TEXT NOT NULL,
  revoked_at TEXT
);

CREATE TABLE IF NOT EXISTS public.companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Legal', 'Ilegal')),
  image_url TEXT,
  ojk_number TEXT,
  base_likes INTEGER NOT NULL DEFAULT 0 CHECK (base_likes >= 0),
  trust_level INTEGER NOT NULL DEFAULT 0 CHECK (trust_level BETWEEN 0 AND 100),
  limit_text TEXT,
  tenor TEXT,
  interest TEXT,
  admin_fee TEXT,
  address TEXT,
  description TEXT NOT NULL,
  source_url TEXT,
  source_checked_at TEXT,
  publication_status TEXT NOT NULL DEFAULT 'draft'
    CHECK (publication_status IN ('draft', 'published', 'archived')),
  featured INTEGER NOT NULL DEFAULT 0 CHECK (featured IN (0, 1)),
  version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  updated_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  deleted_at TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS companies_name_nocase_uq
ON public.companies (lower(name));

CREATE TABLE IF NOT EXISTS public.company_likes (
  company_id INTEGER NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  PRIMARY KEY (company_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  display_name TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT NOT NULL CHECK (char_length(comment) BETWEEN 3 AND 2000),
  base_likes INTEGER NOT NULL DEFAULT 0 CHECK (base_likes >= 0),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'hidden')),
  moderation_note TEXT,
  moderated_by TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  moderated_at TEXT,
  created_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  updated_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  deleted_at TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS reviews_one_per_user_company
ON public.reviews(company_id, user_id)
WHERE user_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.review_likes (
  review_id INTEGER NOT NULL REFERENCES public.reviews(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  PRIMARY KEY (review_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.reports (
  id TEXT PRIMARY KEY,
  reporter_user_id TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  reporter_name TEXT NOT NULL,
  reporter_email TEXT NOT NULL,
  company_id INTEGER REFERENCES public.companies(id) ON DELETE SET NULL,
  company_name TEXT NOT NULL,
  description TEXT NOT NULL CHECK (char_length(description) BETWEEN 10 AND 5000),
  evidence_url TEXT,
  status TEXT NOT NULL DEFAULT 'new'
    CHECK (status IN ('new', 'in_review', 'resolved', 'rejected', 'archived')),
  admin_note TEXT,
  handled_by TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  handled_at TEXT,
  created_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  updated_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  ),
  deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS public.site_settings (
  key TEXT PRIMARY KEY,
  value_json TEXT NOT NULL,
  is_public INTEGER NOT NULL DEFAULT 1 CHECK (is_public IN (0, 1)),
  updated_by TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  updated_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  )
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT,
  before_json TEXT,
  after_json TEXT,
  ip_address TEXT,
  user_agent TEXT,
  created_at TEXT NOT NULL DEFAULT (
    to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  )
);

CREATE INDEX IF NOT EXISTS sessions_user_idx
ON public.sessions(user_id, revoked_at, expires_at);

CREATE INDEX IF NOT EXISTS companies_public_idx
ON public.companies(publication_status, deleted_at, featured);

CREATE INDEX IF NOT EXISTS reviews_company_idx
ON public.reviews(company_id, status, deleted_at);

CREATE INDEX IF NOT EXISTS reports_status_idx
ON public.reports(status, deleted_at, created_at);

CREATE INDEX IF NOT EXISTS audit_created_idx
ON public.audit_logs(created_at DESC);

-- Data API tidak boleh mengakses tabel aplikasi secara langsung. API Express
-- memakai koneksi backend PostgreSQL, sedangkan semua tabel tetap dilindungi RLS.
ALTER TABLE public.app_schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DO $revoke_data_api$
DECLARE
  target_role TEXT;
BEGIN
  FOR target_role IN
    SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')
  LOOP
    EXECUTE format(
      'REVOKE ALL PRIVILEGES ON TABLE public.app_schema_migrations, public.users, public.sessions, public.companies, public.company_likes, public.reviews, public.review_likes, public.reports, public.site_settings, public.audit_logs FROM %I',
      target_role
    );
    EXECUTE format(
      'REVOKE ALL PRIVILEGES ON SEQUENCE public.companies_id_seq, public.reviews_id_seq, public.audit_logs_id_seq FROM %I',
      target_role
    );
  END LOOP;
END;
$revoke_data_api$;
